gladly-team/tab

- web/package.json
- web/scripts/start.js
- web/yarn.lock
Make `relay-compiler` recompile automatically when the source JS or schema changes. When source JS changes, recompile and let Webpack handle hot reload; when schema changes, just restart the server and recompile (server restart needed for `babel-plugin-relay`).
We're not using Relay compiler's built-in `--watch` because it doesn't watch schema by default.
> Fix relay compile

- web/src/js/components/General/AuthUserComponent.js
- web/src/js/constants.js
- web/src/js/utils/cognito-auth.js
* Undo keeping the user ID token in memory, because it expires after 1 hour
* Keep the user ID in localStorage to remove the need for an additional request to Cognito
> Fix flaws in Cognito

- web/src/js/components/User/UserBackgroundImageComponent.js
- web/src/js/components/User/__tests__/UserBackgroundImageComponent.test.js
- web/src/js/utils/local-bkg-settings.js
* Ensure background component style is correct when rendering without any background settings in local storage
* Message parent frame (extension new tab page) with background settings on every mount to make sure settings on the two pages stay in sync
> Fix background bugs

- dynamodb/fixtures/UserWidgetsData.json
- web/src/js/components/Settings/Widgets/WidgetsSettingsComponent.js
Fixes error: Expected prop `widget` to be supplied to `Relay(WidgetSettings)`, but got `undefined`.
> Fix undefined `widgets` props values in widgets settings

- web/src/js/components/Widget/Widgets/Clock/ClockWidgetComponent.js
Previously the Clock widget used `"k:mm"` to format 24 hour time but the correct format-code is `H`, not `k`. Changed moment format to `"H:mm"` for 24 hour time (starts at 0).
Fixes #152
> Format MomentJS for 24 Hour Time

- web/src/js/components/Authentication/FirebaseAuthenticationUI.js
There’s a bug with Google sign-in failing on Firefox.
> Try IDP auth redirect instead of popup

- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/SignInIframeMessage.js
- web/src/js/navigation/navigation.js
- web/src/js/routes/Route.js
- web/src/js/utils/__tests__/utils.test.js
- web/src/js/utils/utils.js
Fixes #188 
When the app is rendered within an iframe (e.g. within an extension's new tab page) and the user is unauthenticated, show an intermediary view with a button to open the sign-in page outside of the iframe.
> Fix sign-in error within iframe

- web/src/js/components/General/AuthUserComponent.js
Due to #151, some users might not have an email address and will see errors on the new tab page. Redirect them to restart the authentication flow.
> Redirect the user from newtab page if they’re missing an email

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/createUser.test.js
- graphql/database/users/createUser.js
- web/data/schema.graphql
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/mutations/CreateNewUserMutation.js
Previously, we fired the analytics "account created" event every time a user signed in, regardless of whether they were truly a brand new user or were just a returning user. This should only fire the event for brand new users.
> Accurate analytics "account created" event

- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/DashboardContainer.js
- web/src/js/components/Dashboard/LogAccountCreationComponent.js
- web/src/js/components/Dashboard/LogAccountCreationContainer.js
- web/src/js/components/Dashboard/__tests__/LogAccountCreationComponent.test.js
- web/src/js/mutations/CreateNewUserMutation.js
Fire the "account created" event when a user opens their first tab. Previously, we fired this after account creation.
> Change "account created" analytics event trigger

- dynamodb/serverless.yml
- graphql/database/userRevenue/__tests__/logRevenue.test.js
- graphql/database/userRevenue/logRevenue.js
Will recreate and use string type instead of number type for `dfpAdvertiserId` field, because some IDs are >32 bits.
> Delete UserRevenueLog table

- web/src/js/components/Dashboard/LogRevenueComponent.js
- web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
Switch away from logging revenue when an ad is viewable and back to logging when the ad slot has finished rendering.
> Log revenue on ad render

- web/package.json
- web/src/js/ads/__mocks__/adsEnabledStatus.js
- web/src/js/ads/__tests__/ads.test.js
- web/src/js/ads/__tests__/adsEnabledStatus.test.js
- web/src/js/ads/ads.js
- web/src/js/ads/adsEnabledStatus.js
- web/src/js/ads/prebid/__mocks__/prebidConfig.js
- web/src/js/ads/prebid/__mocks__/prebidModule.js
- web/src/js/components/Dashboard/LogTabComponent.js
- web/src/js/components/Dashboard/__tests__/LogTabComponent.test.js
- web/src/js/constants.js
- web/src/js/mutations/__mocks__/LogTabMutation.js
- web/src/js/utils/__mocks__/extension-messenger.js
- web/src/js/utils/__mocks__/localstorage-mgr.js
- web/src/js/utils/__tests__/local-bkg-settings.test.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/__tests__/utils.test.js
- web/src/js/utils/local-user-data-mgr.js
- web/yarn.lock
Stop showing ads after a user opens >=150 tabs in a single UTC day. Fixes part of #202.
* Track daily tabs opened in localStorage
* Check count of today's tabs opened in localStorage before loading ads
> Daily ad cap

- web/src/js/ads/__mocks__/consentManagement.js
- web/src/js/ads/__tests__/consentManagement.test.js
- web/src/js/ads/consentManagement.js
- web/src/js/components/App/App.js
- web/src/js/components/App/__tests__/App.test.js
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/AuthenticationView.js
- web/src/js/components/Authentication/FirebaseAuthenticationUI.js
- web/src/js/components/Background/BackgroundImagePickerComponent.js
- web/src/js/components/Campaign/StickerCampaignComponent.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/LogConsentDataComponent.js
- web/src/js/components/Dashboard/LogRevenueComponent.js
- web/src/js/components/Dashboard/__tests__/LogConsentDataComponent.test.js
- web/src/js/components/Settings/Account/AccountComponent.js
- web/src/js/components/Settings/Account/AccountContainer.js
- web/src/js/components/Settings/Account/__tests__/AccountComponent.test.js
- web/src/js/components/Settings/Background/BackgroundSettingsComponent.js
- web/src/js/components/User/UserBackgroundImageComponent.js
* Log consent data when it's updated on the accounts page
* Manage our own callback registration for listening for consent change from the the consent management platform, because Quantcast Choice's callback registration isn't ideal
* Add TODOs to stop using `componentWillMount`, which is deprecated and could cause memory leaks with server-side rendering
> Improve user data consent logging

- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/__tests__/__snapshots__/Authentication.test.js.snap
The rgba background was buggy because the underlying background is not always white.
> Change auth background rgba to 100% opacity

- web/public/index.html
Disable "Display Persistent Consent Link" because we handle the persistent link ourselves.
> Update Quantcast Choice options

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/createUser.test.js
- graphql/database/users/__tests__/logUserExperimentGroups.test.js
- graphql/database/users/createUser.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/__tests__/experiments.test.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/General/__tests__/AuthUserComponent.test.js
- web/src/js/mutations/CreateNewUserMutation.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/experiments.js
Some tests, like the anonymous user sign0n, assign the user to test groups on the client side before user creation. This PR makes sure we log the user's test group for the anonymous user sign-in when we create the user.
* Add a numeric `testGroupAnonSignIn` field to the User model
* Add an `ExperimentGroupsType` GraphQL object
* Send an "experiment groups" object in the mutation when creating a new user, then store the user's experiment groups in the database
> Log the user's test groups on user creation

- graphql/database/base/BaseModel.js
- graphql/database/base/__tests__/BaseModel-queries.test.js
- graphql/database/widgets/__tests__/setUpWidgetsForNewUser.test.js
- graphql/database/widgets/setUpWidgetsForNewUser.js
- graphql/database/widgets/userWidget/UserWidgetModel.js
- graphql/database/widgets/userWidget/__tests__/updateUserWidgetConfig.test.js
- graphql/database/widgets/userWidget/__tests__/updateUserWidgetEnabled.test.js
- graphql/database/widgets/userWidget/updateUserWidgetConfig.js
- graphql/database/widgets/userWidget/updateUserWidgetEnabled.js
Fixes #322 
This PR prevents updates on non-existing database items (prevent items with missing fields) and prevents creations on existing items by default (prevent data loss by overwrite).
> Safer database item creation and update

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/createUser.test.js
- graphql/database/users/createUser.js
- web/data/schema.graphql
- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Dashboard/FirstTabView.js
- web/src/js/components/Dashboard/__tests__/FirstTabView.test.js
- web/src/js/components/General/__tests__/AuthUserComponent.test.js
- web/src/js/constants.js
- web/src/js/mutations/CreateNewUserMutation.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/local-user-data-mgr.js
This PR starts sending the client-created "approximate extension install time" when creating a new user. We also create a UUID "extension install ID" on `/newtab/first-tab/` and include it. We store these values on the user when they're available.
> Log install data when creating a new user

- web/src/index.js
See: https://blog.sentry.io/2017/03/27/tips-for-reducing-javascript-error-noise
> Whitelist our domains to filter Sentry errors

- web/src/js/components/Settings/Account/AccountComponent.js
- web/src/js/components/Settings/Account/__tests__/AccountComponent.test.js
- web/src/js/components/Settings/Profile/InviteFriendComponent.js
- web/src/js/components/Settings/Profile/ProfileStatsComponent.js
- web/src/js/components/Settings/Profile/__tests__/InviteFriendComponent.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileStatsComponent.test.js
When the user is anonymous (does not have an email or username), show alternative text/placeholders for the referral URL component, the account page, and stats page.
> Make email and username optional in components

- web/package.json
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/navigation/navigation.js
- web/src/js/utils/__mocks__/utils.js
- web/src/js/utils/utils.js
- web/yarn.lock
Also support a `noredirect=true` URL parameter for the authentication page to avoid redirecting anonymous users back to the dashboard.
> Show a prompt on the dashboard to ask anonymous users to sign in

- graphql/utils/experiments.js
- web/e2e-tests/__tests__/basics.test.js
- web/src/js/utils/feature-flags.js
The anonymous user sign-in experiment will break this test due to random group assignment. Re-enable this test after we end that experiment.
>  Disable the authentication redirect acceptance test for now

- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/SignInIframeMessage.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Authentication/__tests__/SignInIframeMessage.test.js
- web/src/js/components/Authentication/__tests__/__snapshots__/SignInIframeMessage.test.js.snap
- web/src/js/navigation/navigation.js
- web/src/js/theme/defaultV1.js
If the user was previously using the new tab page anonymously, but we're requiring them to sign in, show a custom message on the authentication pages to explain why we're asking them to sign in. Do not show this message to other users.
> Fix showing an explanation for mandatory anonymous sign-ins

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/logUserExperimentGroups.test.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/ads/__tests__/adSettings.test.js
- web/src/js/ads/adSettings.js
- web/src/js/constants.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/__tests__/feature-flags.test.js
- web/src/js/utils/experiments.js
- web/src/js/utils/feature-flags.js
Enable a test to show some new users various ad sizes and other new users the standard ad sizes.
* Add `testGroupVariousAdSizes` to user model
* Assign new users to the control ("standard") or experimental ("various") group, 50/50 split
* Only show new ad sizes to users in the experimental group
* Enable the feature flag for various ad sizes
> Enable experiment with various ad sizes 

- web/src/js/ads/__mocks__/adSettings.js
- web/src/js/ads/__tests__/adSettings.test.js
- web/src/js/ads/adSettings.js
- web/src/js/ads/amazon/__tests__/amazonBidder.test.js
- web/src/js/ads/amazon/amazonBidder.js
- web/src/js/ads/google/__tests__/setUpGoogleAds.test.js
- web/src/js/ads/google/setUpGoogleAds.js
- web/src/js/ads/prebid/__tests__/prebidConfig.test.js
- web/src/js/ads/prebid/prebidConfig.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/utils/__tests__/feature-flags.test.js
- web/src/js/utils/feature-flags.js
* Add support for a 3rd rectangle ad (which is disabled by feature flag)
* Disable the "various ad sizes" test
* Centralize logic for showing a various number of ads
> Support varying numbers of ad units (between 0 and 3)

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/ads/__tests__/adSettings.test.js
- web/src/js/ads/adSettings.js
- web/src/js/constants.js
- web/src/js/utils/__mocks__/experiments.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/__tests__/feature-flags.test.js
- web/src/js/utils/experiments.js
- web/src/js/utils/feature-flags.js
* Add an (inactive) experiment to test a third ad on the new tab page
* Enable the third ad feature, because it's now gated behind the test group
* Refactor the client-side experiment logic to make it easier to add new experiments
> Set up third ad experiment

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/ads/__tests__/adSettings.test.js
- web/src/js/ads/adSettings.js
- web/src/js/ads/mockDisplayAd.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/experiments.js
Set up logic for an experiment to show only one ad on the new tab page for the first 24 hours for users who are in an experimental group. After 24 hours, show the default number of ads. The control group will see the default number of ads immediately.
> Set up the "one ad for new users" experiment

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/ads/__tests__/adSettings.test.js
- web/src/js/ads/adSettings.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/constants.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/experiments.js
- web/src/js/utils/local-user-data-mgr.js
Set up an experiment in which we show new users a message that the ads are raising money for charity. The message appears above the leaderboard ad and will remain for 4 hours after the user joins unless the user dismisses it.
> Set up "ad explanation" experiment

- web/src/js/components/Campaign/CampaignBase.js
- web/src/js/components/Campaign/HeartDonationCampaignComponent.js
- web/src/js/components/Dashboard/DashboardComponent.js
* Add a minimum width for the dashboard with horizontal scroll to prevent the campaign from covering the widgets.
* Also, increase the Hearts goal for the GiveDirectly campaign
> Make campaign less intrusive on skinny screens

- graphql/utils/__tests__/dev-tools.test.js
- graphql/utils/dev-tools.js
- lambda/__mocks__/uuid/v4.js
- lambda/package.json
- lambda/src/firebase-authorizer/__tests__/firebase-authorizer.test.js
- lambda/src/firebase-authorizer/firebase-authorizer.js
- web/src/js/components/Search/SearchView.js
- web/src/js/components/Search/__tests__/SearchView.test.js
- web/src/js/relay-env.js
**Note:** this PR should include a handful of commits I recently pushed to master on accident.
* Change our authorizer Lambda function to allow requests with a placeholder "unauthenticated" value for the Authorization header. This authorizes unauthenticated requests to our GraphQL endpoint.  We use a placeholder string for the header value because API Gateway otherwise [automatically rejects the request](https://docs.aws.amazon.com/apigateway/latest/developerguide/configure-api-gateway-lambda-authorization-with-console.html"): "If a specified identify source is missing, null, or empty, API Gateway returns a 401 Unauthorized response without calling the authorizer Lambda function."
* Change our GraphQL authorization logic to allow null user IDs
* Make the `withUserId` higher-order …
> Allow unauthenticated users to use search

- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Donate/DonateHeartsControlsComponent.js
- web/src/js/components/MoneyRaised/MoneyRaisedComponent.js
- web/src/js/components/Widget/Widgets/Bookmarks/BookmarkChip.js
Lazy load:
* `react-sparkle`
* the campaign component
* the bookmark edit dialog
There's likely more we can lazy-load, such as the popover menus on the top-right and perhaps the actual widget components themselves.
I disabled some tests because [Enzyme doesn't yet support React.Suspense and React.lazy](https://github.com/airbnb/enzyme/issues/1917). Let's reenable these tests when Enzyme adds support.
> Lazy load some non-critical resources on the new tab

- graphql/data/schema.js
- graphql/database/users/__tests__/logSearch.test.js
- graphql/database/users/logSearch.js
- web/data/schema.graphql
- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/SearchResults.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
- web/src/js/components/Search/__tests__/SearchResults.test.js
- web/src/js/mutations/LogSearchMutation.js
- web/src/js/mutations/__tests__/LogSearchMutation.test.js
* When logging a search event, pass a "source" value equal to the "src" URL parameter
* Log the source value to UserSearchLog. It will only log valid search values:
* `chrome`: a search originating from the Chrome browser extension
* `ff`: a search originating from the Firefox browser extension
* `self`: a search originating from the search page; i.e. searching again
* `tab`:  a search originating from the Tab for a Cause new tab page search widget
* When searching from the Search for a Cause page, set the "src" URL parameter value to "self"
* Now, we should update the browser extensions to append the appropriate "src" value
> Log search source

- web/src/js/components/Dashboard/HeartsComponent.js
- web/src/js/components/Dashboard/HeartsContainer.js
- web/src/js/components/Dashboard/MaxHeartsDropdownMessageComponent.js
- web/src/js/components/Dashboard/UserMenuComponent.js
- web/src/js/components/Dashboard/__tests__/HeartsComponent.test.js
- web/src/js/components/Dashboard/__tests__/MaxHeartsDropdownMessageComponent.test.js
- web/src/js/components/Dashboard/__tests__/UserMenuComponent.test.js
- web/src/js/components/Search/SearchMenuComponent.js
- web/src/js/components/Search/__tests__/SearchMenuComponent.test.js
- web/src/js/constants.js
This PR makes the Hearts component able to show separate messages when the user has earned the maximum daily "hearts from tabs" and when the user has earned the maximum daily "hearts from searches" .
> Show "max hearts from searching" message when needed

- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/SearchResults.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
- web/src/js/components/Search/__tests__/SearchResults.test.js
This is because the ad blocker may block the search request entirely, and we won't know there's an error, which leaves the page with extra scrolling space and a floating pagination element at the bottom.
> Show "unable to search" when an ad blocker is enabled

- lambda/src/search-app-lambda-edge/__tests__/search-app-lambda-edge.test.js
- lambda/src/search-app-lambda-edge/search-app-lambda-edge.js
TODO: after deploying this, update the CloudFront references to new edge function versions.
> Only returned pre-rendered HTML for the search index page

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/constructExperimentActionsType.test.js
- graphql/database/users/__tests__/logUserExperimentActions.test.js
- graphql/database/users/__tests__/logUserExperimentGroups.test.js
- graphql/database/users/constructExperimentActionsType.js
- graphql/database/users/logUserExperimentActions.js
- graphql/database/users/logUserExperimentGroups.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/package.json
- web/src/js/__mocks__/browser-detect.js
- web/src/js/components/App/__tests__/App.test.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/DashboardContainer.js
- web/src/js/components/Dashboard/NotificationComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Dashboard/__tests__/NotificationComponent.test.js
- web/src/js/constants.js
- web/src/js/mutations/LogUserExperimentActionsMutation.js
- web/src/js/mutations/__tests__/LogUserExperimentActionsMutation.test.js
- web/src/js/navigation/navigation.js
- web/src/js/utils/__tests__/detectBrowser.test.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/detectBrowser.js
- web/src/js/utils/experiments.js
- web/yarn.lock
* Create an experiment to show an notification about Search for a Cause
* Detect the client browser so we can send the user to the appropriate extension store when they click
* Log when a user joins their experiment group so we can add people on a rolling basis
* Log whether a user dismisses or clicks through the notification, and hide the notification when they do
> Set up the "search intro" experiment

- web/public/index.html
- web/src/js/ads/__tests__/ads.test.js
- web/src/js/ads/__tests__/handleAdsLoaded.test.js
- web/src/js/ads/amazon/__tests__/amazonBidder.test.js
- web/src/js/ads/amazon/amazonBidder.js
- web/src/js/ads/handleAdsLoaded.js
- web/src/js/ads/indexExchange/__tests__/indexExchangeBidder.test.js
- web/src/js/ads/prebid/__tests__/prebidConfig.test.js
- web/src/js/components/Dashboard/LogRevenueComponent.js
- web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
- web/src/js/utils/__tests__/test-utils.test.js
- web/src/js/utils/__tests__/utils.test.js
- web/src/js/utils/test-utils.js
- web/src/js/utils/utils.js
This ensures it's always defined when used. It addresses "Cannot read property 'ads' of undefined" bugs.
> Use the tab global from a module

- web/src/js/ads/__tests__/ads.test.js
- web/src/js/ads/ads.js
- web/src/js/ads/google/__mocks__/getGoogleTag.js
- web/src/js/ads/indexExchange/__mocks__/indexExchangeBidder.js
- web/src/js/ads/indexExchange/__tests__/indexExchangeBidder.test.js
- web/src/js/ads/indexExchange/indexExchangeBidder.js
- web/src/js/components/Dashboard/LogRevenueComponent.js
- web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
- web/src/js/utils/__tests__/utils.test.js
- web/src/js/utils/utils.js
This PR improves revenue logging to include the highest Index Exchange bids for a slot. If the winning Index Exchange bid is higher than the winning Prebid bid, we log that revenue value.
> Log Index Exchange revenue if it is the winning bid

- web/src/js/components/Dashboard/LogRevenueComponent.js
- web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
When Prebid/IX bids have a value of zero, we should still set the the "aggregationOperation" to "MAX" in the revenue log mutation
> Fix a failure to log revenue when Amazon has bids but Prebid/IX don't

- web/__mocks__/firebase/app.js
- web/src/js/authentication/__mocks__/user.js
- web/src/js/authentication/__tests__/user.test.js
- web/src/js/authentication/helpers.js
- web/src/js/authentication/user.js
- web/src/js/components/General/AuthUserComponent.js
- web/src/js/components/General/__tests__/AuthUserComponent.test.js
- web/src/js/components/General/withUserId.js
- web/src/js/components/General/withUserId.test.js
To manually test auth functionality, make sure:
- New user sign-up flow works
- Returning user sign-up flow works
- Unauthed new tab page redirects to sign-in
- Unauthed search page works as expected
- Authed sign-in page redirects to the dashboard
> Clean up "get current user" functions

- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/General/__tests__/withUser.test.js
- web/src/js/components/General/withUser.js
Add anonymous user authentication server-side user creation in the `withUser` HOC to make it more likely that it provides a functional user. This also makes authentication and user creation logic a little more modular. We still restrict anonymous user creation to within 30 seconds of adding the extension to limit noisy/unnecessary anonymous user creation.
To confirm user creation works as expected:
1. delete the local Firebase user (clear IndexedDB)
2. set the local storage "install time" to now or in the future
3. load a component using `withUser`: it should auth the user, create the user server-side, then render the child component with the newly-created user
> Create users in `withUser` when possible

- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/Campaign/CampaignBaseView.js
- web/src/js/components/General/__tests__/withUser.test.js
- web/src/js/components/General/withUser.js
- web/src/js/components/Search/SearchMenuQuery.js
By default, `withUser` will redirect the user to an authentication page if the user is not fully signed up (e.g. does not have a username).
> In `withUser`, redirect to an auth page if the user is not fully authed

- web/src/js/components/Background/BackgroundCustomImagePickerComponent.js
- web/src/js/components/General/__mocks__/withUser.js
- web/src/js/components/General/withUser.js
- web/src/js/components/Settings/Account/AccountView.js
- web/src/js/components/Settings/Account/__tests__/AccountView.test.js
- web/src/js/components/Settings/Background/BackgroundSettingsView.js
- web/src/js/components/Settings/Background/__tests__/BackgroundSettingsView.test.js
- web/src/js/components/Settings/Profile/ProfileDonateHeartsView.js
- web/src/js/components/Settings/Profile/ProfileInviteFriendView.js
- web/src/js/components/Settings/Profile/ProfileStatsView.js
- web/src/js/components/Settings/Profile/__tests__/ProfileDonateHeartsView.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileInviteFriendView.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileStatsView.test.js
- web/src/js/components/Settings/SettingsPageComponent.js
- web/src/js/components/Settings/Widgets/WidgetsSettingsView.js
- web/src/js/components/Settings/Widgets/__tests__/WidgetsSettingsView.test.js
- web/src/js/components/Settings/__tests__/SettingsPageComponent.test.js
The `withUser` higher-order component is a cleaner and more flexible way to get the user ID than the AuthUser component. It also removes the invisible "magic" of setting the userId in QueryRenderer variables.
This PR replaces `AuthUser` in the settings page views. Another PR should replace it in the Dashboard component, at which point we can deprecate `AuthUser`.
> Replace `AuthUser` component with `withUser` HOC in settings

- dynamodb/serverless.yml
- s3/serverless.yml
- web/serverless.yml
Addresses part of #582 
By default, we will retain these resources even when the stack deletes them:
* DynamoDB tables
* S3 buckets
* Cloudfront distributions
In previous commits, I confirmed DynamoDB tables are retained after deletion.
> Set resource DeletionPolicy in Cloudformation stack

- dynamodb/package.json
- dynamodb/serverless.yml
- graphql/package.json
- graphql/serverless.yml
- lambda/package.json
- lambda/serverless-lambda-edge.yml
- lambda/serverless-lambda.yml
- s3/package.json
- s3/serverless.yml
- web/package.json
- web/serverless.yml
Addresses part of #582 
In prior commits, I confirmed:
* Deleting a DynamoDB table fails with this stack policy
* Deleting the stack policy from serverless.yml does not remove the stack policy from Cloudformation
This is a multi-PR deployment.
**First deployment (this PR):**
**Second deployment:**
**Third deployment:**
> Set restrictive stack policies on all stacks

- web/src/js/components/Authentication/__tests__/__snapshots__/EnterUsernameForm.test.js.snap
- web/src/js/components/General/UsernameField.js
- web/src/js/components/General/__tests__/__snapshots__/UsernameField.test.js.snap
- web/src/js/utils/__tests__/utils.test.js
- web/src/js/utils/utils.js
Fixes #591 
* Disallow `@` and space characters in username
* Clarify that the username is for Tab for a Cause. Some users think it's their email address or Google account username.
> Add additional username validation

- web/src/js/components/Search/SearchMenuComponent.js
- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
* Move the intro message higher (overlapping the search results line break) so it's visually distinct from the search results
* Make the intro message background a teal color
* For users without the extension installed, add a second button that links to the extension store page, plus an extra sentence in the intro
> Make search intro more prominent with extension CTA

- graphql/data/schema.js
- graphql/utils/experiments.js
- web/data/schema.graphql
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/NotificationComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Dashboard/__tests__/NotificationComponent.test.js
- web/src/js/utils/__tests__/experiments.test.js
- web/src/js/utils/experiments.js
* Adds another experiment group to the "search intro" experiment, in which we send interested users directly to the Search for a Cause landing page
* Reenables the experiment, expanding from 10% to 20% of existing users 
* Fixes #579
> Enable search intro experiment v2

- web/src/js/components/Search/SearchApp.js
- web/src/js/components/Search/SearchAuthRedirect.js
- web/src/js/components/Search/SearchMenuComponent.js
- web/src/js/components/Search/SearchMenuQuery.js
- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/__tests__/SearchApp.test.js
- web/src/js/components/Search/__tests__/SearchAuthRedirect.test.js
- web/src/js/components/Search/__tests__/SearchMenuComponent.test.js
- web/src/js/components/Search/__tests__/SearchMenuQuery.test.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
- web/src/js/navigation/navigation.js
- web/src/js/utils/__tests__/search-utils.test.js
- web/src/js/utils/search-utils.js
Show a "Sign in" button on the search results page.
To limit the clutter, we do not always show the "Sign in" button when the user is not signed in. The logic to display the "Sign in" and "Add extension" buttons is:
* If the user has *not* installed the extension:
* Show the "Add extension" button
* Do not show the "Sign in" button, even if the user is not signed in
* If the user *has* installed the extension and is *not* signed in:
* Do not show the "Add extension" button
* Show the "Sign in" button
* If the user *has* installed the extension and *is* signed in:
* Do not show the "Add extension" button
* Do not show the "Sign in" button -- instead, show the Hearts and settings components in the user menu
**One exception**: we will not show the "Add extension" button when there is no `q` …
> Search results page "Sign in" button

- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Donate/CharityComponent.js
- web/src/js/components/General/ErrorMessage.js
- web/src/js/components/General/__tests__/ErrorMessage.test.js
- web/src/js/components/Settings/Account/AccountView.js
- web/src/js/components/Settings/Background/BackgroundSettingsView.js
- web/src/js/components/Settings/Profile/InviteFriendComponent.js
- web/src/js/components/Settings/Profile/ProfileDonateHeartsComponent.js
- web/src/js/components/Settings/Profile/ProfileDonateHeartsView.js
- web/src/js/components/Settings/Profile/ProfileInviteFriendComponent.js
- web/src/js/components/Settings/Profile/ProfileInviteFriendView.js
- web/src/js/components/Settings/Profile/ProfileStatsComponent.js
- web/src/js/components/Settings/Profile/ProfileStatsView.js
- web/src/js/components/Settings/Profile/StatComponent.js
- web/src/js/components/Settings/Profile/__tests__/ProfileDonateHeartsComponent.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileInviteFriendComponent.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileStatsComponent.test.js
- web/src/js/components/Settings/Profile/__tests__/StatComponent.test.js
- web/src/js/components/Settings/SettingsChildWrapperComponent.js
- web/src/js/components/Settings/SettingsPageComponent.js
- web/src/js/components/Settings/Widgets/WidgetsSettingsView.js
- web/src/js/components/Settings/__tests__/SettingsChildWrapperComponent.test.js
- web/src/js/components/Settings/__tests__/SettingsPageComponent.test.js
This is part one of adding some settings and profile pages to the search app.
* Update to new MUI components for all pages and components we might use in the search app, because the search app does not support the old version of `material-ui`
* Remove fade-in animation from settings pages
* Make sure the ErrorMessage snack bar component animates as expected
* If an error occurs when loading a settings page, don't auto-hide the error message snack bar
* Add a bunch of tests
> Update components in settings/profile pages

- web/src/js/components/App/App.js
- web/src/js/components/Settings/SettingsPageComponent.js
- web/src/js/components/Settings/TabSettingsPageComponent.js
- web/src/js/components/Settings/__tests__/SettingsPageComponent.test.js
- web/src/js/components/Settings/__tests__/TabSettingsPageComponent.test.js
This PR is part two of adding some settings and profile pages to the search app.
This PR should not change anything for the end user. It refactors the SettingsPage component into an app-agnostic wrapper for content and creates a settings page specifically for Tab for a Cause.
> Make the settings page more modular

- web/src/js/authentication/__tests__/helpers.test.js
- web/src/js/authentication/helpers.js
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Donate/CharityComponent.js
- web/src/js/components/Donate/DonateHeartsControlsComponent.js
- web/src/js/components/General/__tests__/withUser.test.js
- web/src/js/components/General/withUser.js
- web/src/js/components/Search/SearchApp.js
- web/src/js/components/Search/SearchMenuQuery.js
- web/src/js/components/Search/Settings/SearchProfileInviteFriendComponent.js
- web/src/js/components/Search/Settings/SearchProfileInviteFriendView.js
- web/src/js/components/Search/Settings/SearchSettingsPageComponent.js
- web/src/js/components/Search/Settings/__tests__/SearchProfileInviteFriendComponent.test.js
- web/src/js/components/Search/Settings/__tests__/SearchProfileInviteFriendView.test.js
- web/src/js/components/Search/Settings/__tests__/SearchSettingsPageComponent.test.js
- web/src/js/components/Search/__tests__/SearchApp.test.js
- web/src/js/components/Search/__tests__/SearchMenuQuery.test.js
- web/src/js/components/Settings/Account/AccountComponent.js
- web/src/js/components/Settings/Profile/InviteFriendComponent.js
- web/src/js/components/Settings/Profile/ProfileDonateHeartsComponent.js
- web/src/js/components/Settings/Profile/ProfileInviteFriendComponent.js
- web/src/js/components/Settings/Profile/ProfileStatsComponent.js
- web/src/js/components/Settings/Profile/StatComponent.js
- web/src/js/components/Settings/Profile/__tests__/InviteFriendComponent.test.js
- web/src/js/components/Settings/TabSettingsPageComponent.js
- web/src/js/components/Settings/__tests__/TabSettingsPageComponent.test.js
- web/src/js/navigation/__tests__/navigation.test.js
- web/src/js/navigation/navigation.js
This PR is part three of adding some settings and profile pages to the search app.
* Create three search app pages: `/search/profile/donate/`, `/search/profile/invite/`, and `/search/account/`
* Create a separate "invite friends" page for Search, because referrer rewards aren't yet supported
* Redirect to auth if an unauthenticated user tries to visit a Search settings page
* In the `withUser` higher-order component, use an "app" option argument to redirect to the appropriate auth page with either Search or Tab branding
* Use consistent shadowing for Paper components in the settings pages
* Tweak styling on the "donate Hears" page
> Create some profile/settings pages for Search

- web/src/js/components/Search/SearchResultsBing.js
- web/src/js/components/Search/TextAdSearchResult.js
- web/src/js/components/Search/WebPageSearchResult.js
- web/src/js/components/Search/__tests__/SearchResultsBing.test.js
- web/src/js/components/Search/getMockBingSearchResults.js
- web/src/js/components/Search/searchResultsStyles.js
* Make visited links (web results or text ads) a purple-ish color
* Fix a bug where the active links were underlined in red
* Prevent the scroll position from jumping around when returning to the search results page from another website
> Make sure visited search result links have a different color

- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/SearchResultsBing.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
- web/src/js/components/Search/__tests__/SearchResultsBing.test.js
We've been keeping the search query, search result page number, and search source in state in the SearchPageComponent when it's actually state derived from the `location.search` URL parameter values. It adds complexity and might be causing bugs. Remove these from state altogether.
> Don't set search state that's derived from the `location` prop

- web/src/js/components/Search/SearchRandomQueryView.js
- web/src/js/components/Search/__tests__/SearchRandomQueryView.test.js
Importantly, this preserves the `src` URL param value.
> Preserve URL params when redirecting from /search/random/

- web/src/js/components/General/__tests__/withUser.test.js
- web/src/js/components/General/withUser.js
- web/src/js/components/Search/SearchPageComponent.js
- web/src/js/components/Search/__tests__/SearchPageComponent.test.js
* Add two new options to `withUser`: one to default to using a null user during prerendering, and another to allow rendering HTML before we determine the auth status (for faster rendering)
* Make the search results page render prior to determining the user's auth status
* Make sure we successfully prerender the search results page's HTML
> Make `withUser` compatible with build-time HTML pre-rendering

- web/public/index.html
- web/src/js/components/Search/__tests__/fetchBingSearchResults.test.js
- web/src/js/components/Search/fetchBingSearchResults.js
- web/src/js/utils/test-utils.js
Remove an ill-advised pre-fetched search results query timeout and retry. This can break the second query a user makes on the page, leaving them with the same results as the first query, because we would use the pre-fetched query results for the "first" time on the second search.
As a precaution, also add query matching to ignore fetched queries if the query somehow changes.
> Fix a bug where searching a new query fails on a slow network/CPU

- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/DashboardContainer.js
- web/src/js/components/Dashboard/UserMenuComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Dashboard/__tests__/UserMenuComponent.test.js
- web/src/js/constants.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/local-user-data-mgr.js
Create a new Search for a Cause introduction button that appears in the user menu. Meanwhile, keep the original "beta" Search intro message.
* Show the text-heavy, "beta" intro message to all users who:
* haven't already searched
* haven't already clicked/dismissed the intro message
* haven't already interacted with the intro in our previous experiment
* have opened at least three tabs but fewer than 100 tabs
* Show the sparkly "Double your impact" search intro button to all users who:
* aren't seeing the search intro message above
* haven't already searched
* haven't already clicked the intro button
* have opened at least 150 tabs
> New search introduction button

- web/src/js/components/Authentication/AuthenticationView.js
- web/src/js/components/Authentication/__tests__/AuthenticationView.test.js
- web/src/js/components/Campaign/CampaignBaseView.js
- web/src/js/components/Campaign/__tests__/CampaignBaseView.test.js
- web/src/js/components/Dashboard/DashboardView.js
- web/src/js/components/Dashboard/__tests__/DashboardView.test.js
- web/src/js/components/General/QueryRendererWithUser.js
- web/src/js/components/General/__mocks__/QueryRendererWithUser.js
- web/src/js/components/General/__tests__/QueryRendererWithUser.test.js
- web/src/js/components/Search/SearchMenuQuery.js
- web/src/js/components/Search/Settings/SearchProfileInviteFriendView.js
- web/src/js/components/Search/Settings/__tests__/SearchProfileInviteFriendView.test.js
- web/src/js/components/Search/__tests__/SearchMenuQuery.test.js
- web/src/js/components/Settings/Account/AccountView.js
- web/src/js/components/Settings/Account/__tests__/AccountView.test.js
- web/src/js/components/Settings/Background/BackgroundSettingsView.js
- web/src/js/components/Settings/Background/__tests__/BackgroundSettingsView.test.js
- web/src/js/components/Settings/Profile/ProfileDonateHeartsView.js
- web/src/js/components/Settings/Profile/ProfileInviteFriendView.js
- web/src/js/components/Settings/Profile/ProfileStatsView.js
- web/src/js/components/Settings/Profile/__tests__/ProfileDonateHeartsView.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileInviteFriendView.test.js
- web/src/js/components/Settings/Profile/__tests__/ProfileStatsView.test.js
- web/src/js/components/Settings/Widgets/WidgetsSettingsView.js
- web/src/js/components/Settings/Widgets/__tests__/WidgetsSettingsView.test.js
- web/src/js/mutations/__tests__/DonateVcMutation.test.js
- web/src/js/mutations/__tests__/LogReferralLinkClickMutation.test.js
- web/src/js/mutations/__tests__/LogSearchMutation.test.js
- web/src/js/mutations/__tests__/LogUserExperimentActionsMutation.test.js
Create a customized query renderer that handles server-side user creation, which simplifies query renderer logic elsewhere.
> Use a customized query renderer

- graphql/data/schema.js
- graphql/database/globals/__tests__/getCampaign.test.js
- graphql/database/globals/__tests__/getCampaignData.test.js
- graphql/database/globals/getCampaign.js
- graphql/database/globals/getCampaignData.js
- graphql/database/globals/globals.js
- graphql/utils/redis.js
- web/data/schema.graphql
- web/src/js/components/Campaign/CampaignBaseView.js
- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/DashboardContainer.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
We'll use the Campaign object to fetch the new users who join during a campaign. Gradually, we can move more campaign logic to the server-side to reduce dependence on pushing new client code to launch campaigns.
> Create a server-side Campaign object

- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/UserMenuComponent.js
- web/src/js/components/Dashboard/UserMenuContainer.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
- web/src/js/components/Dashboard/__tests__/UserMenuComponent.test.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/local-user-data-mgr.js
This adds an icon to the user menu when the user closes the "tree planting" campaign. We should remove or generalize this code when the campaign is over.
> Add ability to reopen the tree campaign after closing it

- web/src/js/components/Dashboard/DashboardComponent.js
- web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
Make sure it's hidden when a campaign is not live.
> Fix a bug with the campaign reopen button

- web/src/js/components/Dashboard/DashboardComponent.js
When users max out ads in a day, we hide them. However, we don't want to remove them in the same tab they were loaded.
> Fix a bug where ads would disappear after loading

- graphql/database/base/BaseModel.js
- graphql/database/base/__tests__/BaseModel-queries.test.js
- graphql/database/donations/__tests__/donateVc.test.js
- graphql/database/donations/donateVc.js
- graphql/database/test-utils.js
- graphql/database/userRevenue/__tests__/logRevenue.test.js
- graphql/database/userRevenue/logRevenue.js
- graphql/database/users/__tests__/createUser.test.js
- graphql/database/users/__tests__/logTab.test.js
- graphql/database/users/logTab.js
- graphql/database/widgets/userWidget/__tests__/updateUserWidgetConfig.test.js
- graphql/database/widgets/userWidget/__tests__/updateUserWidgetEnabled.test.js
- graphql/database/widgets/userWidget/updateUserWidgetConfig.js
- graphql/database/widgets/userWidget/updateUserWidgetEnabled.js
- graphql/utils/exceptions.js
* Create a custom error, `DatabaseConditionalCheckFailedException`, to throw when AWS DynamoDB returns a "ConditionalCheckFailedException" during item create/update
* Try logging revenue 3 times instead of 2 when it fails with key conflicts
* Try logging tabs 3 times when it fails with key conflicts (currently failing immediately)
* Use await/async in BaseModel
* Clean up BaseModel tests to explicitly set database operation mocks and deprecate the `setMockDBResponse` helper function, which just complicates tests
* Use a helper function to create mock AWS "ConditionalCheckFailedException" errors in tests
> Handle database ConditionalCheckFailed errors

- graphql/database/users/UserModel.js
- graphql/database/users/rewardReferringUser.js
- graphql/utils/__tests__/error-logging.test.js
- graphql/utils/error-logging.js
- graphql/utils/exceptions.js
The errors are expected when a user removes their credentials (e.g. they delete the Firebase item in IndexedDB) and aren't helpful.
We may eventually want to address the root issue, for example by not making requests when the user token is missing. There's a scenario where the logs are helpful; e.g., we introduce a bug in authorization and a spike in these exceptions would help us address it.
> Don't log UnauthorizedQueryException errors

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/UserModel.test.js
- graphql/database/users/__tests__/setV4Enabled.test.js
- graphql/database/users/setV4Enabled.js
- web/data/schema.graphql
- web/src/js/authentication/__tests__/user.test.js
- web/src/js/authentication/user.js
- web/src/js/components/Authentication/Authentication.js
- web/src/js/components/Authentication/AuthenticationContainer.js
- web/src/js/components/Authentication/EnterUsernameForm.js
- web/src/js/components/Authentication/__tests__/Authentication.test.js
- web/src/js/components/Authentication/__tests__/EnterUsernameForm.test.js
- web/src/js/constants.js
- web/src/js/mutations/CreateNewUserMutation.js
- web/src/js/mutations/SetV4BetaMutation.js
- web/src/js/mutations/__mocks__/SetV4BetaMutation.js
- web/src/js/mutations/__tests__/SetV4BetaMutation.test.js
- web/src/js/navigation/navigation.js
- web/src/js/utils/__mocks__/v4-beta-opt-in.js
- web/src/js/utils/__tests__/local-user-data-mgr.test.js
- web/src/js/utils/__tests__/v4-beta-opt-in.test.js
- web/src/js/utils/local-user-data-mgr.js
- web/src/js/utils/v4-beta-opt-in.js
The goal is to be able to send users through this "legacy" app's sign-in flow, but upon sign-in completion, permanently direct them to the Tab v4 beta app. If the user clears storage and signs back in, they should still see the Tab v4 beta app.
* Add `v4BetaEnabled` field to the user profile
* On sign-in, if "tab.newUser.isTabV4Enabled" === "true" in local storage or the `v4BetaEnabled` field is set on the user's profile, call an endpoint to set a cookie that opts into the Tab V4 beta
* On sign-in, if "tab.newUser.isTabV4Enabled" === "true" but the the `v4BetaEnabled` field is **not** set on the user's profile, set it before signing in. This way, if the user clears storage or logs in elsewhere, they will continue to see the Tab v4 beta app.
> Support opting users into Tab v4 beta during sign-in

- dynamodb/Dockerfile
Closes #833
I bumped the node version as well because it gave me a deprecation warning with version 6.
> Bump ubuntu and node to latest LTS

- web/package.json
- web/yarn.lock
**Basic CMP functionality**
* A new user has the expected default privacy string. Clear the CMP data, then run:
```js
__uspapi("getUSPData", 1, (uspData, success) => { console.log('cmp responded:', uspData, success)})
```
The `uspString` property value should be `1YNN`.
Works on:
* GDPR should not apply. Run:
```js
__tcfapi('getTCData', 2, (tcData, success) => { console.log('cmp responded:', tcData, success)})
```
The `gdprApplies` property value should be `false`.
Works on:
**CMP Consent Dialog**
* The user's account page should show a "Do Not Show My Info" link that opens the CCPA dialog.
Works on:
* The user's choice should persist. Open the dialog, opt out of data sale, and save. Refresh the app, open the dialog, and confirm you are still opted out.
Works on:
* After opting out of …
> Upgrade tab-cmp

- web/src/js/components/General/ConditionalWrapper.js
- web/src/js/components/General/__tests__/ConditionalWrapper.test.js
- web/src/js/components/Widget/Widgets/Bookmarks/BookmarkChip.js
- web/src/js/components/Widget/Widgets/Bookmarks/__tests__/BookmarkChip.test.js
Added tests.
Closes #622 
I couldn't just replace the span with an "a" or Link because it caused the page to change when user clicked on the bookmark to edit it. And I didn't want to conditionally render an "a" or Link and copy and paste all the children components with all the duplicate code, so I made a "ConditionalWrapper" that can be used to wrap the children with a Link when not editing.
> Open bookmarks in new tab with middle mouse button

- web/src/js/root.js
I noticed that when you do `yarn run start:newtab` or `yarn run start:search` the browser opens on the root path and not on  `/newtab/` or `/search/`, so I added a redirect for that.
> Web start script redirects to newtab or search

- graphql/database/users/__tests__/rewardReferringUser.test.js
- graphql/database/users/rewardReferringUser.js
I actually think we don't want to use getOrCreate here.  If we do, a user might refer another user on tab legacy and we'd end up creating and giving them referral bonuses on our v4 UserImpact document.  If a user does refer someone to Tab for Cats, then their UserImpact record must already be created so I don't think it's an issue
> fix updating impact from referrer

- .travis.yml
- lambda/src/newtab-app-lambda-edge/__tests__/newtab-lambda-edge.test.js
- lambda/src/newtab-app-lambda-edge/newtab-app-lambda-edge.js
- web/serverless.yml
This PR adds CloudFront Lambda@Edge logic to route all auth-related requests to the legacy Tab app. It will route:
* any page (no file type suffix) with a path beginning with `/newtab/auth`
* any non-page resource (**must** have a file type suffix) and `Referer` with a path beginning with `/newtab/auth`
This is a workaround until Tab v4 has a fully-implemented auth flow.
Outstanding: we should make sure Tab v4 refreshes upon logout rather than navigating within the app router so that we'll show the Tab legacy auth page.
> Send all /newtab/auth* traffic to the legacy Tab app

- graphql/database/invitedUsers/__tests__/utils.test.js
- graphql/database/invitedUsers/utils.js
this allows us to get advanced sendgrid stats/analytics on our referral emails so that we don't have to calculate them
> add a category to referral emails for tracking

- .travis.yml
- s3/serverless.yml
- web/serverless.yml
Use new ACM certificate for *.gladly.io.
**Note:** We still do not support `www.` subdomain redirect to non-www. To do this right and support HTTPS, we'd likely need separate CloudFront distributions. An alternative is to only redirect non-HTTPS `www` using an S3 distribution, like we do currently for https://gladly.io.
> Update SSL certificate

- graphql/data/schema.js
- graphql/database/users/UserModel.js
- graphql/database/users/__tests__/createUser.test.js
- graphql/database/users/__tests__/getOrCreateTruexId.test.js
- graphql/database/users/createUser.js
- graphql/database/users/getOrCreateTruexId.js
- web/data/schema.graphql
verified on local front end that truex id is passed down and stays consistent between calls
> add truex id to user model

- web/serverless.yml
- web/src/js/navigation/navigation.js
- web/src/js/utils/__tests__/v4-beta-opt-in.test.js
This removes the need to rewrite /v4/api* requests in our Next.js app, freeing us to upgrade to a later version of Next.js.
> Add a new v4 API path, /newtab/api

- .travis.yml
- lambda/package.json
- lambda/serverless-lambda-edge.yml
- lambda/src/newtab-app-lambda-edge/newtab-app-lambda-edge.js
- lambda/src/search-app-lambda-edge/__tests__/search-app-lambda-edge.test.js
- lambda/src/search-app-lambda-edge/__tests__/searchURLByRegion.test.js
- lambda/src/search-app-lambda-edge/search-app-lambda-edge.js
- lambda/src/search-app-lambda-edge/searchURLByRegion.js
- lambda/src/utils/lambda-arg-utils.js
- lambda/yarn.lock
- web/serverless.yml
Redirect search requests from `/search/v2/` to a localized Yahoo search engine results page.
> Set up v2 search endpoint

- graphql/data/schema.js
- web/data/schema.graphql
The LogSearch mutation currently expects a plain user ID. This PR supports passing the user's Relay global ID.
> Modify LogSearch mutation to support global userID

- .travis.yml
- graphql/.env
- graphql/database/experiments/__tests__/getUserFeature.test.js
- graphql/database/experiments/__tests__/getUserFeatures.test.js
- graphql/database/experiments/__tests__/growthbookUtils.test.js
- graphql/database/experiments/features.js
- graphql/database/experiments/growthbookUtils.js
- graphql/database/users/getUserSearchEngine.js
- scripts/assign-env-vars.js
* Set up a test experiment
* Set `GROWTHBOOK_ENV` environment variable across GraphQL environments
* Disable some feature logic that's broken until other code is enabled
> Set up a test experiment

- graphql/database/constants.js
- graphql/database/search/__tests__/searchEngines.test.js
- graphql/database/search/searchEngineData.js
- graphql/database/search/searchEngines.js
- graphql/database/users/UserModel.js
- graphql/database/users/UserSearchLogModel.js
- graphql/database/users/UserSearchSettingsLogModel.js
- graphql/database/users/UserSwitchSearchPromptLogModel.js
- graphql/database/users/__tests__/createSearchEnginePromptLog.test.js
- graphql/database/users/createSearchEnginePromptLog.js
This will enable both engines. I also shoehorned some logic into the CreateSearchEnginePromptLogMutation to correctly update UserModel.
> TFAC-891: Enabling SFAC, Yahoo as Search Engines

- graphql/data/schema.js
- graphql/database/experiments/__tests__/growthbookUtils.test.js
- graphql/database/experiments/features.js
- graphql/database/experiments/getUserFeature.js
- graphql/database/experiments/growthbookUtils.js
- graphql/database/users/__tests__/getUserNotifications.test.js
- graphql/database/users/getUserNotifications.js
* This should not affect prod until the feature is enabled
* When the feature is enabled, return a notification from `user.notifications`, indicating to the client to show the 2022 user survey
> Backend: feature to show notification about user survey

- .travis.yml
- graphql/data/schema.js
- graphql/database/constants.js
- graphql/database/search/SearchEngineModel.js
- graphql/database/search/__tests__/SearchEngineModel.test.js
- graphql/database/search/searchEngineData.js
- graphql/database/users/__tests__/getUserSearchEngine.test.js
- graphql/database/users/getUserSearchEngine.js
- lambda/src/search-app-lambda-edge/__tests__/search-app-lambda-edge.test.js
- lambda/src/search-app-lambda-edge/search-app-lambda-edge.js
- web/data/schema.graphql
This PR tackles two distinct pieces:
* Provide a personalized Search for a Cause URL to improve analytics: add a `SearchEnginePersonalized` type that includes reporting dimensions in the `searchUrlPersonalized` field
* Update the search endpoint to forward Search for a Cause reporting dimensions in a URL parameter
This PR is a no-op when deployed until we:
* update the search Lambda@Edge version in a subsequent deployment
* update the client behavior: https://github.com/gladly-team/tab-web/pull/356
> [TFAC-1035] Improve reporting dimensions for search

- .travis.yml
- lambda/serverless-lambda-edge.yml
- lambda/src/search-app-lambda-edge/__tests__/search-app-lambda-edge.test.js
- lambda/src/search-app-lambda-edge/search-app-lambda-edge.js
- web/serverless.yml
* For "version 3" of the search endpoint, call the SearchRequest SNS topic. Don't change this for existing production behavior for `/search/` or `/search/v2/`.
* Bug fix, affecting production search behavior: don't lowercase URL parameter values when passing dimensions to Yahoo. Doing so leads to bad cause IDs.
* For debugging: return an `X-Tab-Stage-Debug` response header that's the same as the `X-Tab-Stage` request header value. Remove this after manual QA in other deploy stages.
> TFAC-1047: call search request SNS topic from edge lambda

- graphql/database/experiments/experimentConstants.js
- graphql/database/experiments/features.js
- graphql/database/users/__tests__/getShouldShowSfacIcon.test.js
- graphql/database/users/getShouldShowSfacIcon.js
Before deploying, merge https://github.com/gladly-team/tab-web/pull/378 and #1334.
> TFAC-1121: launch experiment to show SFAC icon to existing users

- graphql/data/schema.js
I did run `updateSchema`, but I presume there were no changes to schema.graphql since no APIs or return types changed.
> Adding new ImpactMetric and GroupImpactMetric Types to schema.js

- graphql/database/groupImpact/updateGroupImpactMetric.js
We are expecting an integer. This just makes sure it always is such when updating.
> Round updateGroupImpactMetric logTab

- graphql/data/schema.graphql
- graphql/data/schema.js
- graphql/database/cause/CauseModel.js
- graphql/database/cause/__tests__/CauseModel.test.js
- graphql/database/cause/causes/blackEquity/causeData.js
- graphql/database/cause/causes/cats/causeData.js
- graphql/database/cause/causes/endingHunger/causeData.js
- graphql/database/cause/causes/globalHealth/causeData.js
- graphql/database/cause/causes/reproductiveHealthCauseData.js
- graphql/database/cause/causes/teamseas/causeData.js
- graphql/database/cause/causes/trees/causeData.js
- graphql/database/cause/causes/ukraine/causeData.js
- graphql/database/experiments/experimentConstants.js
- graphql/database/experiments/features.js
- graphql/database/test-utils.js
- graphql/database/users/__tests__/getLandingPagePhrase.test.js
- graphql/database/users/getLandingPagePhrase.js
- web/data/schema.graphql
We want to test a more direct statement on the tab v4 page “chip”:
Added the new field to cause, built out new experiment.
> [TFAC-1023]: Test out a stronger "supporting" statement on the new tab page

- web/src/js/components/Shop/ShopComponent.js
- web/src/js/components/Shop/__tests__/ShopComponent.test.js
There was an issue when we redirected the user out of the shop auth flow that a 404 page would show up. We needed to return null instead of nothing.
> Fixed small bug with 404 page showing up in shop auth flow

- graphql/database/cause/__tests__/getCauseByUser.test.js
- graphql/database/cause/getCauseByUser.js
Fixed issue where errors were being thrown on no causeId. 
This issues was caused by removing the default of cats being the causeId. 
Now if a user is using v4 and does not have a causeId set it will add the cat's cause id to their profile. If they are a legacy user and not v4 we return null when cause is looked up.
TODO(spicer): make 'no-cause' a constant some where. Just did not know quickly where to put this.
> Fixed issue where errors were being thrown on no causeId

- lambda/package.json
- lambda/serverless-lambda-edge.yml
- lambda/src/newtab-app-lambda-edge/__tests__/newtab-lambda-edge.test.js
- lambda/src/newtab-app-lambda-edge/newtab-app-lambda-edge.js
Just like auth with newtab/shop we need to make sure all requests go to legacy. This PR updates our cloudfront edge function to support this.
> Update edge function to support the new shop auth flow.

- lambda/package.json
- lambda/serverless-lambda-edge.yml
Lambda use to have a 25meg limit. It recently has been updated to 50megs. This makes it so we no longer have to limit our build size. We were having issues where all dependencies where not uploading.
> Removed pattern matching when building lambda

- web/public/index.html
Adds URL parameter support to easily switch between ad providers during testing phase.
- **URL Parameter Support**: Can now use `?ads=buysellads` or `?ads=raptive` to set the ad provider
- **Automatic Persistence**: URL parameter updates localStorage for subsequent visits
- **Testing Mode Maintained**: Still defaults to Raptive unless explicitly overridden
1. When the page loads, it checks for an `ads` URL parameter
2. If present and valid (`buysellads` or `raptive`), it updates localStorage
3. The stored preference persists across page loads until changed or cleared
- **Enable Buy/Sell Ads**: Visit `/newtab/?ads=buysellads`
- **Enable Raptive**: Visit `/newtab/?ads=raptive`
- The parameter only needs to be used once - preference is saved
```javascript
// Enable Buy/Sell Ads …
```
> Add URL parameter support for ad provider selection
