gladly-team/tab

lambda/.gitignore
lambda/serverless.yml

Adds a cognito arn. Can be tested via:
`curl https://<deploy-url>/dev/hearts -H "Authorization: <id-token>"`

Added profile and cognito arn

---

dynamodb/fixtures/CharityData.json
graphql/data/database.js
graphql/data/schema.graphql
graphql/data/schema.js
graphql/data/schema.json
web/data/schema.json
web/src/js/components/App.js

An end-to-end example on to how to display data from dynamoDB.

Connect GraphQL to DynamoDB

---

dynamodb/fixtures/FeatureData.json
dynamodb/package.json
dynamodb/tables.json
graphql/data/database.js
graphql/data/schema.js

Josiah this is closely related with your current branch, hope it can be a good starting point on fetching and mutating data using dynamoDB.

Using mutations to add new items to database.

---

web/src/js/components/Authentication/Authentication.js
web/src/js/components/Authentication/LoginForm.js
web/src/js/utils/cognito-auth.js
web/src/js/utils/tfac-mgr.js

Check if confirmed after signup and skip confirmation code. Add Authentication with old tfac endpoint.

Tfac auth in tab

---

docker-compose.yml
graphql/server.js

Service runs independently on a docker container. 
1- Run app normally.
2- Check localhost:8001

Add dynamodb local admin

---

dynamodb/fixtures/BackgroundImages.json
dynamodb/fixtures/CharityData.json
dynamodb/fixtures/FeatureData.json
dynamodb/fixtures/UserData.json
dynamodb/fixtures/UserLevels.json
dynamodb/fixtures/UserWidgetsData.json
dynamodb/fixtures/WidgetsData.json
graphql/database/base/__tests__/model.test.js
graphql/database/base/model.js
graphql/database/users/base.js
graphql/database/users/updateUserVc.js
graphql/database/utils.js
graphql/database/widgets/userWidget/userWidget.js

- Add updated timestamp to the base model.
- Add created timestamp to the base model.

Add base fields

---

web/src/js/utils/cognito-auth.js

Keep Cognito user in memory and prevent duplicate requests per page load.

Reduce Cognito requests

---

web/src/js/utils/__tests__/local-bkg-settings.test.js
web/src/js/utils/local-bkg-settings.js

Fix a bug that prevented loading the background image photo URL from localStorage.

Fix background image load

---

web/public/index.html
web/src/js/components/Donate/CharityComponent.js
web/src/js/components/Widget/Widgets/Bookmarks/BookmarkChip.js
web/src/js/components/Widget/Widgets/Search/CenteredSearch.js
web/src/js/components/Widget/Widgets/Search/DefaultSearch.js

Make sure all links open in the top frame.

Fix links in iframe

---

.travis.yml

* Trying to avoid current broken deploys due to Travis bug: https://github.com/travis-ci/travis-ci/issues/8774
* Should speed up future deploys

Non-sudo TravisCI environment

---

web/package.json
web/src/js/utils/utils.js
web/yarn.lock

Re-add function for username validation.

Fix username entry during signup flow

---

dynamodb/serverless.yml
dynamodb/tables.json
graphql/database/donations/__tests__/donateVc.test.js
graphql/database/donations/donateVc.js
graphql/handler.js

Update DynamoDB schema to match expected schema.

Fix donate hearts

---

.travis.yml
dynamodb/serverless.yml

Recreate VcDonationLog table

---

dynamodb/serverless.yml

Finishing table schema changes from #125

Recreate ReferralDataLog table

---

graphql/database/users/createUser.js
graphql/serverless.yml

Forgot to give GraphQL permission to write to the ReferralDataLog table.

Fix referral data

---

web/src/js/components/Dashboard/DashboardComponent.js

And add a link to the feedback survey.

Delay showing feedback message on dashboard

---

web/serverless.yml
web/src/js/routes/Route.js

Use one Cloudfront distribution to route to our landing page as well as "new tab" app.

Cloudfront domain routing

---

web/src/js/components/Widget/WidgetIconComponent.js
web/src/js/components/Widget/Widgets/Bookmarks/BookmarksWidgetComponent.js

And info that bookmarks will be improving.

Add link to survey feedback note

---

graphql/data/schema.js
graphql/database/base/BaseModel.js
graphql/database/base/__tests__/BaseModel-queries.test.js
graphql/database/donations/__tests__/donateVc.test.js
graphql/database/donations/donateVc.js
graphql/utils/dev-tools.js
web/data/schema.graphql
web/src/js/components/Donate/CharityComponent.js

Fixes #156 
Also fixes a bug in which Hearts donation would subtract Hearts from a user's all-time Hearts count.

Fix double Hearts donation

---

web/src/js/components/Authentication/VerifyEmailMessage.js

Allow restarting sign-in flow from email verification step

---

web/src/js/components/Authentication/Authentication.js
web/src/js/components/Authentication/MissingEmailMessage.js
web/src/js/navigation/navigation.js
web/src/js/routes/Route.js

Fixes #151 
On authentication, check to make sure the user has an email address. If not, show a message asking them to sign in with another method.

Require email address for authed users

---

graphql/database/base/BaseModel.js
graphql/database/base/__tests__/BaseModel-queries.test.js
graphql/migration/migrateUserReferral.js
graphql/serverless.yml

* Support overwriting database "created" and "updated" fields, which is useful when backfilling old data
* Add a lambda function to migrate old user referral data

User referral data migration

---

migration/fixtures-prod/Widgets.json
web/src/js/components/Widget/Widgets/Todos/AddTodoForm.js

 Change to-do list widget display name

---

web/src/js/components/Campaign/CampaignBaseContainer.js
web/src/js/components/Dashboard/DashboardComponent.js

This reverts commit f8fd47f9bb3bc860ef36a9129dd92eacc3bcd726.

Reenable sticker campaign

---

graphql/package.json
web/__mocks__/react-ga.js
web/package.json
web/src/js/analytics/__tests__/facebook-analytics.test.js
web/src/js/analytics/__tests__/google-analytics.test.js
web/src/js/analytics/__tests__/logEvent.test.js
web/src/js/analytics/logEvent.js

* Test Google and Facebook analytics modules
* Log a Facebook `pageview` event on the new tab page

Add analytics tests

---

web/public/index.html
web/src/js/ads/__tests__/handleAdsLoaded.test.js
web/src/js/ads/handleAdsLoaded.js
web/src/js/components/Dashboard/LogRevenueComponent.js
web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
web/src/js/utils/test-utils.js

Log revenue only when ad creative has finished loading

More precise revenue logging

---

.travis.yml
package.json
web/package.json
web/yarn.lock

Use a [fork of Firebase](https://github.com/kmjennison/firebase-js-sdk/commit/d2e3b0f6e83bcade9ffe3a2436767e8560546b72) that throws `event.target.error` in the IndexedDB `onerror` event. This hopefully helps us better understand Firefox authentication problems.

Debug Firebase IDB errors

---

.travis.yml
scripts/assign-env-vars.js
web/src/js/ads/prebid/prebidConfig.js

Update some settings (changes in Prebid 1.x):
* Update sizes to use `mediaTypes.banner.sizes`
* Set `enableSendAllBids: false`
* Set `publisherDomain`

Change some Prebid settings

---

graphql/serverless.yml
web/public/index.html

This enables the consent management UI, consent logging, passing consent to partners, and the consent management control on the user's "Account" page.

Enable EU consent

---

web/src/js/ads/__tests__/ads.test.js
web/src/js/ads/ads.js
web/src/js/ads/amazon/__tests__/amazonBidder.test.js
web/src/js/ads/amazon/amazonBidder.js

See: https://ams.amazon.com/webpublisher/uam/docs/web-integration-documentation/integration-guide/javascript-guide/api-reference.html

Fix Amazon TAM GDPR settings to match latest documentation

---

web/package.json
web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/DashboardContainer.js
web/src/js/components/Dashboard/NewUserTourComponent.js
web/src/js/components/Dashboard/NewUserTourContainer.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
web/src/js/components/Dashboard/__tests__/NewUserTourComponent.test.js
web/src/js/components/Settings/Profile/InviteFriendComponent.js
web/src/js/components/Settings/Profile/InviteFriendContainer.js
web/src/js/components/Settings/Profile/ProfileInviteFriendComponent.js
web/src/js/components/Settings/Profile/ProfileInviteFriendContainer.js
web/src/js/components/Settings/Profile/__tests__/InviteFriendComponent.test.js
web/src/js/components/User/UserMenuComponent.js
web/src/js/components/User/__tests__/UserMenuComponent.test.js
web/src/js/components/Widget/WidgetsComponent.js
web/src/js/components/Widget/__tests__/WidgetsComponent.test.js
web/src/js/constants.js
web/yarn.lock

Closes #194 
* Add an intro tour for new users
* Add tests for the dashboard
* Make InviteFriend component more reusable and use it in the tour

New user introduction/tour

---

web/src/js/components/Dashboard/PostUninstallView.js
web/src/js/components/Dashboard/__tests__/PostUninstallView.test.js
web/src/js/navigation/navigation.js
web/src/js/routes/Route.js

Add a page that handles post-uninstall user feedback: https://tab.gladly.io/newtab/uninstalled/

Add a post-uninstall view to get user feedback

---

web/package.json
web/yarn.lock

Upgrade Jest and fix test coverage

---

web/src/js/ads/prebid/prebidConfig.js
web/src/js/components/App/App.js
web/src/js/components/Dashboard/LogConsentDataComponent.js
web/src/js/components/Settings/Account/AccountComponent.js

Handle errors in determining the EU membership of the client location

---

web/src/js/components/Authentication/EnterUsernameForm.js
web/src/js/components/Authentication/__tests__/EnterUsernameForm.test.js

Check again on the username screen if the user’s email is verified

---

web/src/js/authentication/__tests__/helpers.test.js
web/src/js/authentication/helpers.js

Fix error when checking email verification and the user is not authenticated

---

graphql/database/userRevenue/__tests__/logRevenue.test.js
graphql/database/userRevenue/logRevenue.js

Fix revenue key conflicts

---

.travis.yml
web/src/js/components/Authentication/Authentication.js
web/src/js/components/Authentication/__tests__/Authentication.test.js
web/src/js/utils/__tests__/feature-flags.test.js

In addition, disable the sign-in explanation, which is buggy due to bad logic.

Enable the anonymous sign-in experiment

---

web/public/index.html

**Note:** this is _not_ the same as GTM or GPT.

Add Google Global Site Tag (gtag.js)

---

web/src/js/components/Campaign/StickerCampaignComponent.js
web/src/js/components/Dashboard/LogRevenueComponent.js

Remove all remaining uses of deprecated componentWillMount

---

graphql/data/schema.js
graphql/database/userRevenue/UserRevenueModel.js
graphql/database/userRevenue/__tests__/logRevenue.test.js
graphql/database/userRevenue/logRevenue.js
web/data/schema.graphql
web/src/js/components/Dashboard/LogRevenueComponent.js
web/src/js/components/Dashboard/__tests__/LogRevenueComponent.test.js
web/src/js/mutations/LogUserRevenueMutation.js

Log the ad dimension string along with the revenue logs.

Log ad sizes

---

.travis.yml
scripts/assign-env-vars.js
web/e2e-tests/__tests__/basics.test.js
web/src/js/authentication/__tests__/helpers.test.js
web/src/js/authentication/helpers.js
web/src/js/utils/__tests__/experiments.test.js
web/src/js/utils/__tests__/feature-flags.test.js
web/src/js/utils/experiments.js
web/src/js/utils/feature-flags.js

Disable anon sign-in experiment and remove the associated code.

Remove code for "anon sign-in" experiment

---

web/src/js/utils/__tests__/experiments.test.js
web/src/js/utils/experiments.js

Activate "3rd ad", "one ad for recently-joined users", and "ad explanation" experiments.

Activate ad experiments

---

graphql/data/schema.js
graphql/database/charities/CharityModel.js
graphql/database/charities/__tests__/getCharities.test.js
graphql/database/charities/getCharities.js

This PR allows us to have charities in our database that aren't displayed on the "donate Hearts" page.

Support filtering inactive charities

---

web/src/js/components/Donate/DonateHeartsControlsComponent.js

Also fix a `setState` context bug.

Move "thanks for supporting" into title of the post-Heart-donation message

---

dynamodb/fixtures/CharityData.json
graphql/data/schema.js
graphql/database/charities/CharityModel.js
migration/fixtures-prod/CharityData.json
web/data/schema.graphql
web/src/js/components/Campaign/__tests__/HeartDonationCampaignComponent.test.js
web/src/js/components/Donate/DonateHeartsControlsComponent.js
web/src/js/components/Donate/DonateHeartsControlsContainer.js

Add a caption for the post-donation image, and change the URL for GiveDirectly's mailing list.

Changes to GiveDirectly

---

web/package.json
web/src/js/components/Donate/DonateHeartsControlsComponent.js
web/src/js/components/Donate/__tests__/DonateHeartsControlsComponent.test.js
web/src/js/mutations/DonateVcMutation.js
web/src/js/mutations/__mocks__/DonateVcMutation.js
web/src/js/mutations/__tests__/DonateVcMutation.test.js
web/yarn.lock

* Refactor the mutation used to donate VC: use a Promise, use an object instead of lots of parameters
* Add simple tests for the mutation
* Add a bunch of tests for the DonateHeartsControls component

DonateVcMutation refactor and tests for donating Hearts

---

web/src/js/components/Search/SearchPageComponent.js
web/src/js/components/Search/SearchResults.js
web/src/js/components/Search/__tests__/SearchPageComponent.test.js
web/src/js/components/Search/__tests__/SearchResults.test.js

* Display a message when no search results are returned
* Display a message and log an error when any unexpected errors occur
* Better UX for trying to search an empty search query

Handle some search errors

---

dynamodb/fixtures/CharityData.json
graphql/data/schema.js
graphql/database/charities/CharityModel.js
graphql/database/charities/__tests__/getCharities.test.js
graphql/database/charities/getCharities.js
graphql/integration-tests/fixtures/CharityData.json
graphql/scripts/updateSchema.js
migration/fixtures-prod/CharityData.json
web/data/schema.graphql
web/src/js/components/Settings/Profile/ProfileDonateHeartsContainer.js

This allows to have other charities but only display permanent partners on the "donate Hearts" page.

Support filtering charities by "permanent partner" field

---

web/package.json
web/yarn.lock

Downgrade react-measure to temporarily fix bug

---

web/public/index.html
web/src/js/components/App/App.js
web/src/js/components/Dashboard/DashboardComponent.js

And load the CMP earlier in App.js.

Fix the Quantcast CMP by setting the variable in HTML

---

web/public/search-2019.2.28.14.21.css
web/src/js/components/Search/SearchResults.js
web/src/js/components/Search/YPAConfiguration.js
web/src/js/components/Search/__tests__/YPAConfiguration.test.js

* Add a dividing line between search ads and other search results
* Hide merchant star ratings in ad results

Search ad format tweaks

---

web/.env
web/public/index.html
web/src/js/ads/amazon/README.md
web/src/js/ads/amazon/__mocks__/getAmazonTag.js
web/src/js/ads/amazon/__tests__/amazonBidder.test.js
web/src/js/ads/amazon/amazonBidder.js
web/src/js/utils/__tests__/utils.test.js
web/src/js/utils/utils.js

Use Amazon apstag in a SafeFrame

---

web/src/js/components/Dashboard/UserMenuComponent.js

Fix UI bug in user menu when notification is present

---

web/package.json
web/src/js/__mocks__/blockadblock.js
web/src/js/components/Search/SearchPageComponent.js
web/src/js/components/Search/__tests__/SearchPageComponent.test.js
web/src/js/navigation/navigation.js
web/src/js/utils/__mocks__/detectAdblocker.js
web/src/js/utils/__tests__/detectAdblocker.test.js
web/src/js/utils/detectAdblocker.js
web/yarn.lock

* Add an ad blocker detection util
* Show a message on the search page to ask for whitelisting when an ad blocker is detected

Message about ad blocker whitelisting on search page

---

web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/General/Link.js
web/src/js/components/General/__tests__/Link.test.js
web/src/js/components/Logo/Logo.js
web/src/js/components/Logo/__tests__/Logo.test.js
web/src/js/components/Search/SearchPageComponent.js
web/src/js/components/Search/__tests__/SearchPageComponent.test.js
web/src/js/navigation/navigation.js

* Tweak copy for "search intro" message
* Fix flash of unstyled content caused by our logo's alt text
* Add a feedback button
* Add "beta" label

Search tweaks

---

web/public/index.html
web/src/js/ads/__tests__/ads.test.js
web/src/js/ads/ads.js
web/src/js/ads/google/__mocks__/getGoogleTag.js
web/src/js/ads/indexExchange/__mocks__/getIndexExchangeTag.js
web/src/js/ads/indexExchange/__mocks__/indexExchangeBidder.js
web/src/js/ads/indexExchange/__tests__/getIndexExchangeTag.test.js
web/src/js/ads/indexExchange/__tests__/indexExchangeBidder.test.js
web/src/js/ads/indexExchange/getIndexExchangeTag.js
web/src/js/ads/indexExchange/indexExchangeBidder.js
web/src/js/utils/__tests__/feature-flags.test.js
web/src/js/utils/__tests__/test-utils.test.js
web/src/js/utils/feature-flags.js
web/src/js/utils/test-utils.js

We can enable IX with the URL parameter value `ixDebug=true`.

Add Index Exchange bidder (in debug mode only)

---

dynamodb/serverless.yml
dynamodb/tables.json
graphql/data/schema.js
graphql/database/constants.js
graphql/database/referrals/ReferralLinkClickLogModel.js
graphql/database/referrals/__tests__/ReferralLinkClickLogModel.test.js
graphql/database/referrals/__tests__/logReferralLinkClick.test.js
graphql/database/referrals/logReferralLinkClick.js
graphql/database/tables.js
graphql/integration-tests/utils/table-utils.js
graphql/serverless.yml
lambda/src/utils/tables.js
web/data/schema.graphql
web/src/js/components/Settings/Profile/InviteFriendComponent.js
web/src/js/components/Settings/Profile/InviteFriendContainer.js
web/src/js/components/Settings/Profile/__tests__/InviteFriendComponent.test.js
web/src/js/mutations/LogReferralLinkClickMutation.js
web/src/js/mutations/__mocks__/LogReferralLinkClickMutation.js
web/src/js/mutations/__tests__/LogReferralLinkClickMutation.test.js

Create a table, ReferralLinkClickLog, and log when users click on their referral link. This helps us measure unsuccessful attempts to recruit friends.

Log referral link click

---

graphql/data/schema.js
graphql/database/users/UserModel.js
graphql/database/users/__tests__/constructExperimentActionsType.test.js
graphql/database/users/__tests__/logUserExperimentActions.test.js
graphql/database/users/__tests__/logUserExperimentGroups.test.js
graphql/database/users/constructExperimentActionsType.js
graphql/database/users/logUserExperimentActions.js
graphql/database/users/logUserExperimentGroups.js
graphql/utils/experiments.js
web/data/schema.graphql
web/src/js/components/Dashboard/AssignExperimentGroupsComponent.js
web/src/js/components/Dashboard/AssignExperimentGroupsContainer.js
web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/DashboardContainer.js
web/src/js/components/Dashboard/__tests__/AssignExperimentGroupsComponent.test.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
web/src/js/utils/__tests__/experimentFilters.test.js
web/src/js/utils/__tests__/experiments.test.js
web/src/js/utils/experimentFilters.js
web/src/js/utils/experiments.js

Set up an experiment to show a notification to users who joined >3 days ago and have not recruited any friends.

Set up the "referral notification" experiment

---

dynamodb/serverless.yml
graphql/serverless.yml
lambda/serverless-lambda-edge.yml
lambda/serverless-lambda.yml
s3/serverless.yml
web/serverless.yml

Continues work of PR #584, addressing part of issue #582

Set restrictive stack policy on stacks (deploy 2 of 3)

---

dynamodb/serverless.yml
s3/serverless.yml
web/serverless.yml

Retain certain AWS resources on update/delete

---

dynamodb/package.json
graphql/package.json
lambda/package.json
s3/package.json
web/package.json

Revert force-deployment, used to update stack policies (deploy 3 of 3)

---

web/src/js/components/Authentication/Authentication.js
web/src/js/components/Authentication/AuthenticationView.js
web/src/js/components/Authentication/__tests__/Authentication.test.js

Fix auth flow bug for new users

---

web/src/js/components/Settings/Profile/InviteFriendComponent.js
web/src/js/components/Settings/Profile/__tests__/InviteFriendComponent.test.js

Properly encode the referral URL

---

web/public/index.html
web/src/js/components/Search/__mocks__/getBingMarketCode.js
web/src/js/components/Search/__tests__/fetchBingSearchResults.test.js
web/src/js/components/Search/__tests__/getBingMarketCode.test.js
web/src/js/components/Search/fetchBingSearchResults.js
web/src/js/components/Search/getBingMarketCode.js

* Use the browser's language preference, if sufficient
* If we need a country code on top of the language preference, get it from MaxMind

Send the Bing market code in the mkt parameter

---

web/public/index.html
web/src/js/components/Search/SearchPageComponent.js
web/src/js/components/Search/__tests__/SearchPageComponent.test.js
web/src/js/constants.js
web/src/js/utils/__mocks__/search-utils.js
web/src/js/utils/__tests__/search-utils.test.js
web/src/js/utils/search-utils.js
web/src/js/utils/test-utils.js

"Add extension" button on results page

---

web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/utils/feature-flags.js

This is part one of adding some settings and profile pages to the Search app.

Enable August Charity Spotlight voting

---

web/src/js/components/Dashboard/HeartsComponent.js
web/src/js/components/Dashboard/HeartsContainer.js
web/src/js/components/Dashboard/SettingsButtonComponent.js
web/src/js/components/Dashboard/UserMenuComponent.js
web/src/js/components/Dashboard/UserMenuContainer.js
web/src/js/components/Dashboard/__tests__/HeartsComponent.test.js
web/src/js/components/Dashboard/__tests__/SettingsButtonComponent.test.js
web/src/js/components/Dashboard/__tests__/UserMenuComponent.test.js
web/src/js/components/MoneyRaised/MoneyRaisedComponent.js
web/src/js/components/MoneyRaised/__tests__/MoneyRaisedComponent.test.js
web/src/js/components/Search/SearchMenuComponent.js
web/src/js/components/Search/SearchMenuContainer.js
web/src/js/components/Search/__tests__/SearchMenuComponent.test.js
web/src/js/components/Search/fetchBingSearchResults.js
web/src/js/navigation/navigation.js

Refactor our user menu components to allow for customizable dropdown menus. Make the Search user menu dropdowns link to the appropriate search app pages.

Search results page user menu

---

web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
web/src/js/constants.js
web/src/js/utils/__tests__/experiments.test.js
web/src/js/utils/__tests__/local-user-data-mgr.test.js
web/src/js/utils/experiments.js
web/src/js/utils/local-user-data-mgr.js

Show the introduction to Search for a Cause to all users who haven't yet interacted with it.

Show the new tab search intro notification to everybody

---

web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js

Reverts a merge from yesterday.

Re-enable beta intro to Search for a Cause

---

web/src/js/components/App/App.js
web/src/js/components/App/__tests__/App.test.js
web/src/js/utils/__tests__/feature-flags.test.js
web/src/js/utils/feature-flags.js

TODO: create an issue to describe the problem and potential solutions

Disable EU ad personalization due to CMP bug

---

dynamodb/fixtures/WidgetsData.json
graphql/integration-tests/fixtures/Widgets.json
web/src/js/components/Widget/Widgets/Search/Search.js
web/src/js/components/Widget/Widgets/Search/__tests__/Search.test.js

---
Feel free to squash-all or suggest a different order of commits

Adding duckduckgo as a search engine

---

graphql/data/schema.js
graphql/database/globals/__tests__/createCampaignConfiguration.test.js
graphql/database/globals/__tests__/getCampaign.test.js
graphql/database/globals/createCampaignConfiguration.js
graphql/database/globals/getCampaign.js
graphql/database/globals/getCurrentCampaignConfig.js
graphql/package.json
graphql/serverless.yml
graphql/utils/redis.js
graphql/yarn.lock
redis/serverless.yml
web/data/schema.graphql
web/package.json
web/src/js/components/Campaign/CampaignGenericComponent.js
web/src/js/components/Campaign/CampaignGenericView.js
web/src/js/components/Campaign/__tests__/CampaignGenericComponent.test.js
web/yarn.lock

* Update campaign copy
* Support setting campaign theme colors
* Fix GraphQL permission to access Redis

Set up campaign for Food Bank for NYC

---

web/package.json
web/yarn.lock

Upgrade tab-ads

---

dynamodb/fixtures/UserWidgetsData.json
dynamodb/fixtures/WidgetsData.json
graphql/integration-tests/fixtures/Widgets.json
web/src/js/components/Settings/Widgets/WidgetConfigComponent.js
web/src/js/components/Widget/Widgets/Clock/ClockWidgetComponent.js
web/src/js/components/Widget/Widgets/Clock/__tests__/ClockWidgetComponent.test.js

Add option to show seconds on clock

---

web/src/js/components/Authentication/Authentication.js

I think this should do what is desired, since the onAuthProcessCompleted callback sets the redirect URL for the page.

TFAC-329 Adding Reauthentication Logic with Redirect

---

.travis.yml
lambda/serverless-lambda-edge.yml
lambda/src/search-app-lambda-edge/__tests__/search-app-lambda-edge.test.js
lambda/src/search-app-lambda-edge/search-app-lambda-edge.js
lambda/src/utils/lambda-arg-utils.js
web/serverless.yml

After deploying to prod, follow up with an update to the prod search Lambda@Edge function version.

[TFAC-423] Update search provider

---

web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/DashboardContainer.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js

Reverts gladly-team/tab#913
ok looking over the code reverting both PRs should do the trick

Revert "Set cookie if v4BetaEnabled is true"

---

dynamodb/fixtures/UserMissions.json
graphql/data/schema.js
graphql/database/missions/__tests__/getCurrentUserMission.test.js
graphql/database/missions/__tests__/utils.test.js
graphql/database/missions/utils.js

Revert "Adjusting Utils for new Model Shape"

---

graphql/database/users/__tests__/logTab.test.js
graphql/database/users/logTab.js
web/data/schema.graphql

log tab was counting tabs while mission was in pending state

slightly adjust log tab and add more tests

---

dynamodb/fixtures/Causes.json
graphql/database/cause/CauseModel.js
graphql/database/cause/__tests__/CauseModel.test.js

decided to add theming properties to the backend and pass them down

update cause model to include theming

---

graphql/data/schema.js
graphql/database/experiments/__tests__/getUserFeature.test.js
graphql/database/experiments/__tests__/growthbookUtils.test.js
graphql/database/experiments/experimentConstants.js
graphql/database/experiments/features.js
graphql/database/experiments/getUserFeature.js
graphql/database/experiments/getUserFeatures.js
graphql/database/experiments/growthbookUtils.js
graphql/database/search/__tests__/getSearchEngine.test.js
graphql/database/search/getSearchEngine.js
graphql/database/users/__tests__/getShouldShowYahooPrompt.test.js
graphql/database/users/__tests__/getUserSearchEngine.test.js
graphql/database/users/getShouldShowYahooPrompt.js
graphql/database/users/getUserSearchEngine.js
web/data/schema.graphql

Also included, some refactoring, implementation of `getUserFeature` and some breaking up of shared code.

TFAC-781 Resolvers for Getting User Search Engine

---

dynamodb/fixtures/UserExperiment.json
graphql/data/schema.js
graphql/database/experiments/UserExperimentModel.js
graphql/database/experiments/__tests__/createUserExperiment.test.js
graphql/database/experiments/__tests__/getUserFeatures.test.js
graphql/database/experiments/__tests__/growthbookUtils.test.js
graphql/database/experiments/createUserExperiment.js
graphql/database/experiments/getUserFeatures.js
graphql/database/experiments/growthbookUtils.js
graphql/database/users/getUserSearchEngine.js
graphql/yarn.lock
web/data/schema.graphql

* Fix user context passed from schema
* Make UserExperiment.variationId an integer
* Add UserExperiment.variationValueStr field

Fix and modify user experiment logic

---

graphql/database/backgroundImages/BackgroundImageModel.js
graphql/database/base/test-utils/ExampleDynamoDBModelRangeKey.js
graphql/database/cause/CauseModel.js
graphql/database/charities/CharityModel.js
graphql/database/donations/VCDonationByCharityModel.js
graphql/database/donations/VCDonationModel.js
graphql/database/experiments/UserExperimentModel.js
graphql/database/invitedUsers/InvitedUsersModel.js
graphql/database/missions/MissionModel.js
graphql/database/missions/UserMissionModel.js
graphql/database/referrals/ReferralDataModel.js
graphql/database/referrals/ReferralLinkClickLogModel.js
graphql/database/userDataConsent/UserDataConsentModel.js
graphql/database/userImpact/UserImpactModel.js
graphql/database/userLevels/UserLevelModel.js
graphql/database/userRevenue/UserRevenueModel.js
graphql/database/users/UserModel.js
graphql/database/users/UserSearchLogModel.js
graphql/database/users/UserSearchSettingsLogModel.js
graphql/database/users/UserSwitchSearchPromptLogModel.js
graphql/database/users/UserTabsLogModel.js
graphql/database/videoAdLog/VideoAdLogModel.js
graphql/database/widgets/baseWidget/BaseWidgetModel.js
graphql/database/widgets/userWidget/UserWidgetModel.js

This branch excludes a few models:
- FeatureModel
- CauseModel
- SearchEngineModel
This is because these aren't based on a DynamoDB table anyways. The first one is just a data holder, and the latter two are based on json/js data (and will be converted as we eventually implement the JSONModel).

Changing to DynamoDBModel

---

graphql/serverless.yml

TFAC-1054: set explicit identity source in Firebase authorizer

---

graphql/database/experiments/features.js

This is merged into dev as well.

TFAC-1103 Ending yahoo-search-new-users-v2 test

---

graphql/database/users/UserModel.js

First change, just to keep track on a per user basis who has seen the SFAC Extension prompt.

TFAC-1090 Updated UserModel

---

graphql/database/groupImpact/CauseGroupImpactMetricModel.js
graphql/database/groupImpact/GroupImpactMetricModel.js
graphql/database/groupImpact/__tests__/CauseGroupImpactMetricModel.test.js
graphql/database/groupImpact/__tests__/GroupImpactMetricModel.test.js
graphql/database/groupImpact/__tests__/getGroupImpactMetricForCause.test.js
graphql/database/groupImpact/getGroupImpactMetricForCause.js

To be used in later PRs in schema.js as a resolver.

TFAC-988 Implementing getGroupImpactByCauseId

---

graphql/database/constants.js
graphql/database/experiments/experimentConstants.js
graphql/database/experiments/features.js
graphql/database/users/__tests__/getShouldShowSFACExtensionPrompt.test.js
graphql/database/users/getSfacActivityState.js
graphql/database/users/getShouldShowSfacExtensionPrompt.js

TFAC-1138 Show "Try SFAC" to More Users

---

web/package.json
web/src/js/components/App/App.js
web/src/js/components/Dashboard/DashboardComponent.js
web/src/js/components/Dashboard/DashboardContainer.js
web/src/js/components/Dashboard/SfacExtensionSellNotification.js
web/src/js/components/Dashboard/__tests__/DashboardComponent.test.js
web/yarn.lock

Style changes are in the most recent commit.

Bring back SFACExentensionSellNotification and Fix Styles

---

graphql/database/experiments/features.js

Enables a 3rd ad for a portion of v4 users.

Launch 3rd ad experiment

---

lambda/package.json
lambda/serverless-lambda-edge.yml
lambda/serverless-lambda.yml
lambda/yarn.lock

Upgrade Serverless in lambda sevice

---

graphql/database/users/getUserNotifications.js
web/src/js/utils/feature-flags.js

Show December 2022 campaign notification

---

graphql/.env
web/package.json
web/src/js/authentication/__tests__/user.test.js
web/src/js/authentication/user.js
web/src/setupTests.js
web/yarn.lock

* Swap local-only JWT library to a more appropriate and functional one
* Add Redis env variables to `.env`

Fix dev environment: JWT, env vars

---

graphql/__mocks__/@upstash/redis/with-fetch.js

This will replace actual upstash which should be good for test timeouts.

TFAC-1208: Good Enough Mock Redis

---

web/public/index.html

Installs the js software snippet for getadmiral.com in the head of the index.html

Installed js for getadmiral.com

---

graphql/database/experiments/experimentConstants.js
graphql/database/experiments/features.js
graphql/database/users/getUserNotifications.js
web/src/js/components/Dashboard/DashboardComponent.js

This pull requests removes the Jan 2023 SFAC notification and adds the new Feb2023 notification.
In Jan we voted on which cause to support. This notification announces the winner.

Removed Jan2023 notification and added Feb2023

---

graphql/database/experiments/features.js

Turned on the go live statement.

[TFAC-1023]: Test out a stronger "supporting" statement on the new tab page - go live

---

graphql/database/groupImpact/impactMetricData.js

https://gladly-team.slack.com/archives/C01MVEAQY31/p1676677555242769

TFAC-1233 Adding additional Impact Metrics

---

graphql/data/schema.js

Just fixing a small bug in the code (calling this method wrong).

TFAC-1172 Fixing schema.js Bug

---

graphql/database/cause/causes/reproductiveHealthCauseData.js
graphql/database/groupImpact/__tests__/getNextImpactMetricForCause.test.js
graphql/database/groupImpact/getNextImpactMetricForCause.js
graphql/database/groupImpact/impactMetricData.js

Also added new impact metrics from the google doc.

Turning on GroupImpact for Reproductive Health

---

web/public/index.html

Updated the Admiral code to just track adblockers vs giving user a notification.

---

graphql/database/experiments/experimentConstants.js
graphql/database/experiments/features.js
graphql/database/groupImpact/GroupImpactLeaderboard.js
graphql/database/users/getUserNotifications.js

Launch our promo for Prime day 2023

Launch Prime day 2023

---

web/public/index.html

Installs that JS code for GAM ad blocking notification.

Add google ad manager ad blocking scripts.

---

graphql/data/schema.graphql
graphql/data/schema.js
web/data/schema.graphql

Update Incorrect Field

---

dynamodb/fixtures/CharityData.json
graphql/database/cause/causes.js
graphql/database/cause/causes/endingAnimalSuffering/about.md
graphql/database/cause/causes/endingAnimalSuffering/causeData.js
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step1.subtitle.md
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step1.title.md
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step2.subtitle.md
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step2.title.md
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step3.subtitle.md
graphql/database/cause/causes/endingAnimalSuffering/onboarding.step3.title.md
graphql/database/cause/causes/endingAnimalSuffering/social.email.about.md
graphql/database/cause/causes/endingAnimalSuffering/social.subtitle.md
graphql/database/cause/causes/endingAnimalSuffering/social.title.md

- Implemented new cause: Ending Animal Suffering supporting The Humane League
- Added all required cause configuration and content files
- All tests and linting passing
- Added The Humane League charity to `CharityData.json` fixtures
- Created new cause folder structure under `graphql/database/cause/causes/endingAnimalSuffering/`
- Added `about.md` with cause description
- Created `causeData.js` with all cause configuration
- Added onboarding step files (titles and subtitles)
- Added social sharing files (title, subtitle, email about)
- Imported new cause in `causes.js`
Closes #1669

Fix #1669: Launch new cause: Ending Animal Suffering
